apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshelf-ingress
spec:
  rules:
    - host: the-bookshelf
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: bookshelf-monolith-service
                port:
                  number: 3000