version: '3'
services:
  bookshelf-monolith-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=bookshelf-monolith-db
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
  user-service-db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=user-service-db
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3308:3306"