apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookshelf-ingress
spec:
  rules:
    - host: the-bookshelf
      http:
        paths:
          - path: /api/v1//books/(.*)
            pathType: Prefix
            backend:
              service:
                name: bookshelf-monolith-service
                port:
                  number: 3000
          - path: /api/v1/users/(.*)/comments
            pathType: Prefix
            backend:
              service:
                name: bookshelf-monolith-service
                port:
                  number: 3000
          - path: /api/v1/users/(.*)
            pathType: Prefix
            backend:
              service:
                name: user-service-service
                port:
                  number: 3100